### ISSUE TITLE
Fix address label print position and address layout

### ISSUE THREAD

**Issue by audrius-a** [achrisdale/TNBase#15]
The exact position of the printing of address labels may need adjusting a bit so that the whole address is always on the label.

**Comment by achrisdale** [comment]
Please move the start position of the top row of printing up 4mm, then start each row of printing so that it starts 46mm below the start of the previous row. (The height of each label is 46mm.) the horizontal positions are OK.  A copy of a page of the present address labels will be e-mailed separately.

**Comment by achrisdale** [comment]
Also, please fix the layout of the addresses so that the town name is is on the third line, which is presently blank, leaving the fourth line for the post code.

**Comment by audrius-a** [comment]
The empty line there is not really empty, it's the second line address. Not all addresses have it so it appears as there is just dead space. Do you still want me to split the town and postcode for those that don't have a second line?

**Comment by achrisdale** [comment]
A good point Audrius. District addresses usually go on the 3rd line. I 
notice that The 'County' line isn't used on the address labels.

I have sent some suggestions to Linda (copied below), so please don't 
change it yet.
Hi Linda,
Audrius has replied regarding our request to move the town name to the 3rd 
line on the address labels: I can see now that the third line is used when 
the address is in somewhere like Knowle, so 'Knowle' appears on the third
line which would otherwise be blank. The labelling of the address lines on 
the listener Edit form is: Line 2 'Address', line 3 doesn't have a label,
line 4 is 'Town', line 5 is 'County' which isn't used on address labels,
and line 6 is 'Postcode'.

If you wanted to change the layout, I suppose we could ask for the 2nd
line to be labelled 'District & Town eg: 'Dorridge, Solihull', and the 3rd 
line 'County', and the 4th line 'Postcode'. Removing the 4th and 5th
lines. We would need to check that districts with long names like 'Bentley 
Heath', Chiswick Green' or 'Chelmsley Wood' would still fit on line 3 with 
'Solihull'.

Regards,

Chris

**Comment by audrius-a** [comment]
I'm closing this one as I've repositioned the label. Please create a new issue to change the address format if needed.
